/* Method Register — modules/method-register/module.js
   Built against "MCC. ENG. MET. MRE. SLN101 Method Registry Tracker. 2026 07 15"
   (Strevi Residences). The workbook's SUMMARY sheet is generated by formulas, and
   THOSE FORMULAS ARE THE SPEC. Transcribed verbatim, per trade:

     TOTAL MS (G)   = 'Method Registry 01'!N<trade>  = SUM of N over the trade block
                      — N is 1 per counted item, so this is a COUNT of N=1 rows
     APP (V)        = COUNTIFS(code "*TW*", Status "Approved",              N=1)
     AWC (W)        = COUNTIFS(code "*TW*", Status "Approved w/ Comments",  N=1)
     DIS (X)        = COUNTIFS(code "*TW*", Status "disapproved",           N=1)
     TOTAL SUBMITTED (I) = V + W + X
     PROGRESS (J)   = I / G
     BALANCE  (K)   = G − I
     % APP    (Y)   = V / G
     HIRAC/QCC/MAS/ISD (M/O/Q/S) = SUMIFS(N, <attachment> = "Balance", code "*TW*")
       and % BAL (N/P/R/T) = that / G
     ENGG (AA) / OPS (AB)  = COUNTIFS(code "*TW*", Ball-In "engg"/"ops", N=1)

   ⚠️ `counts` (the workbook's N=1) gates EVERY metric above. The sample workbook
   holds 323 method-statement rows of which only 103 count; ignoring the flag
   over-reports the programme by 3x.

   TWO DEFECTS IN THE WORKBOOK — reproduced, proven, then fixed (both surfaced in
   the Summary's reconciliation note rather than silently corrected):

   1. ⚠️ BALL IN COURT loses most of the register. SUMMARY counts Ball-In "engg"
      and "ops", but the sheet's own vocabulary is Open / Ops / Closed / "-".
      Nobody ever types "engg", so ENGG reads 0 for every trade, and the 79
      counted items sitting at "Open" are attributed to NEITHER column: the block
      accounts for 19 of 103. `ballInCounts()` reports Engineering / Ops / Closed
      / Unassigned so the four add up to the total.
   2. ⚠️ THE TOTAL ROW AVERAGES RATIOS. J18 = AVERAGE(J6:J17) and Y18 =
      AVERAGE(Y6:Y17) — an unweighted mean over 12 trades, five of which have a
      zero target — while every other total on that row is a real SUM. The
      workbook prints 3.49% progress where the aggregate 5/103 is 4.85%.
      `totals()` aggregates; `legacyTotals()` reproduces the average PURELY for
      the reconciliation note. Never report from it. */
window.MethodRegister = (function () {
  'use strict';

  var TABLE = 'method_register';
  var sb = function () { return window.__sb || (window.__sb = supabase.createClient(APP_CONFIG.SUPABASE_URL, APP_CONFIG.SUPABASE_ANON_KEY)); };
  var esc = function (s) { return Fmt.esc(s == null ? '' : String(s)); };
  function ico(name, size) { return (window.Icons && Icons.svg) ? Icons.svg(name, size || 15) : ''; }

  // The 12 trades, in the workbook's own SUMMARY order (also its Sheet1 list).
  var TRADES = [
    ['TW', 'TEMPORARY WORKS'], ['CE', 'CONSTRUCTION EQUIPMENT'], ['ST', 'STRUCTURAL'],
    ['AR', 'ARCHITECTURAL'], ['CV', 'CIVIL WORKS'], ['RC', 'RECTIFICATION WORKS'],
    ['ME', 'MECHANICAL'], ['EE', 'ELECTRICAL'], ['PL', 'PLUMBING'],
    ['FP', 'FIRE PROTECTION'], ['LA', 'LANDSCAPE & AMENITIES'], ['SP', 'OTHER SPECIALTIES']
  ];
  var TRADE_NAME = {}; TRADES.forEach(function (t) { TRADE_NAME[t[0]] = t[1]; });

  var STATUSES = [
    { name: 'Open',                 cls: 'mr-s-open' },
    { name: 'Approved',             cls: 'mr-s-app' },
    { name: 'Approved w/ Comments', cls: 'mr-s-awc' },
    { name: 'Disapproved',          cls: 'mr-s-dis' }
  ];
  var STATUS_ORDER = STATUSES.map(function (s) { return s.name; });
  // The workbook writes 'Approved' with no qualifier and '-' for "nothing yet".
  var LEGACY_STATUS = { '-': '', 'approved w/comments': 'Approved w/ Comments',
    'approved with comments': 'Approved w/ Comments', 'disapprove': 'Disapproved' };

  var BALL_IN = ['Engg', 'Ops', 'Closed', 'Open'];
  var ATTACH = [['hirac_done', 'HIRAC'], ['qcc_done', 'QCC'], ['mas_done', 'MAS'], ['isd_done', 'ISD']];

  var pid = null, PROFILE = null, UID = null, rows = [], canWrite = false, isAdmin = false;
  var view = 'summary', collapsed = {}, projects = [];
  var filters = { q: '', trade: '', status: '', ballin: '', countedOnly: false };

  // ---- helpers -------------------------------------------------------------
  var MNAME = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function fmtDate(s) {
    if (!s) return '';
    var p = String(s).slice(0, 10).split('-');
    if (p.length !== 3 || isNaN(+p[0])) return esc(s);
    return String(+p[2]).padStart(2, '0') + '-' + MNAME[+p[1] - 1] + '-' + String(p[0]).slice(2);
  }
  function pct(n) { return (n * 100).toFixed(1) + '%'; }
  function statusOf(r) {
    var s = (r.status || '').trim();
    var k = LEGACY_STATUS[s.toLowerCase()];
    return k === undefined ? s : k;
  }
  function statusMeta(n) {
    for (var i = 0; i < STATUSES.length; i++) if (STATUSES[i].name === n) return STATUSES[i];
    return null;
  }
  function isItem(r) { return !r.node_kind; }
  function counted(r) { return isItem(r) && r.counts !== false; }
  function ballOf(r) { return (r.ball_in || '').trim(); }

  // ==========================================================================
  // SUMMARY maths — the workbook's formulas, per trade
  // ==========================================================================
  function tradeStats(code) {
    var mine = rows.filter(function (r) { return counted(r) && (r.trade_code || '') === code; });
    var total = mine.length;                       // = SUM(N) over the block
    var app = 0, awc = 0, dis = 0, engg = 0, ops = 0, closed = 0, unassigned = 0;
    var bal = { hirac_done: 0, qcc_done: 0, mas_done: 0, isd_done: 0 };
    mine.forEach(function (r) {
      var s = statusOf(r);
      if (s === 'Approved') app++;
      else if (s === 'Approved w/ Comments') awc++;
      else if (s === 'Disapproved') dis++;
      var b = ballOf(r).toLowerCase();
      if (b === 'engg') engg++; else if (b === 'ops') ops++;
      else if (b === 'closed') closed++; else unassigned++;
      ATTACH.forEach(function (a) { if (!r[a[0]]) bal[a[0]]++; });
    });
    var submitted = app + awc + dis;               // I = V+W+X
    return {
      code: code, name: TRADE_NAME[code] || code, total: total,
      app: app, awc: awc, dis: dis, submitted: submitted,
      balance: total - submitted,
      progress: total ? submitted / total : 0,
      pctApp: total ? app / total : 0,
      engg: engg, ops: ops, closed: closed, unassigned: unassigned,
      bal: bal
    };
  }
  function allTradeStats() { return TRADES.map(function (t) { return tradeStats(t[0]); }); }

  // Aggregate totals — every figure is a real sum, INCLUDING the two percentages.
  function totals(st) {
    var t = { total: 0, app: 0, awc: 0, dis: 0, submitted: 0, balance: 0,
      engg: 0, ops: 0, closed: 0, unassigned: 0,
      bal: { hirac_done: 0, qcc_done: 0, mas_done: 0, isd_done: 0 } };
    st.forEach(function (s) {
      ['total','app','awc','dis','submitted','balance','engg','ops','closed','unassigned']
        .forEach(function (k) { t[k] += s[k]; });
      ATTACH.forEach(function (a) { t.bal[a[0]] += s.bal[a[0]]; });
    });
    t.progress = t.total ? t.submitted / t.total : 0;
    t.pctApp = t.total ? t.app / t.total : 0;
    return t;
  }
  // ⚠️ Reproduces the workbook's AVERAGE(J6:J17) / AVERAGE(Y6:Y17) so the
  // Summary can show WHY its own total differs. Never report from this.
  function legacyTotals(st) {
    var n = st.length || 1;
    return {
      progress: st.reduce(function (a, s) { return a + s.progress; }, 0) / n,
      pctApp:   st.reduce(function (a, s) { return a + s.pctApp; }, 0) / n
    };
  }

  // ==========================================================================
  // Load / save
  // ==========================================================================
  async function load() {
    var host = document.getElementById('mr-view');
    host.innerHTML = skeletonHTML();
    // Keyset-paginated: PostgREST caps a select at 1000 rows and returns no
    // error, and this register runs to ~530 rows per project already.
    var out = [], last = null;
    try {
      for (var i = 0; i < 40; i++) {
        var q = sb().from(TABLE).select('*').eq('project_id', pid).order('id').limit(1000);
        if (last) q = q.gt('id', last);
        var res = await q;
        if (res.error) throw res.error;
        var batch = res.data || [];
        out = out.concat(batch);
        if (batch.length < 1000) break;
        last = batch[batch.length - 1].id;
      }
    } catch (e) {
      host.innerHTML = '<div class="pd-card mr-empty"><h3>Could not load the register</h3><p>' +
        esc(e.message || e) + '</p><p class="mr-mut">If the table is missing, run ' +
        '<code>migrations/0013-method-register.sql</code>.</p></div>';
      return;
    }
    // Display order: sort_order, then the workbook's own numeric seq_no.
    rows = out.sort(function (a, b) {
      var sa = a.sort_order == null ? 1e9 : a.sort_order, sbb = b.sort_order == null ? 1e9 : b.sort_order;
      if (sa !== sbb) return sa - sbb;
      return String(a.seq_no || '').localeCompare(String(b.seq_no || ''), undefined, { numeric: true });
    });
    syncFilterOptions();
    render();
  }

  function skeletonHTML() {
    var out = '';
    for (var i = 0; i < 8; i++) {
      out += '<div class="mr-sk-row"><span class="mr-sk" style="width:12%"></span>' +
        '<span class="mr-sk" style="width:44%"></span><span class="mr-sk" style="width:14%"></span>' +
        '<span class="mr-sk" style="width:12%"></span></div>';
    }
    return '<div class="pd-card mr-skcard" aria-busy="true">' +
      '<div class="mr-sk-head"><span class="mr-spin"></span>Loading register…</div>' + out + '</div>';
  }

  // ==========================================================================
  // Render
  // ==========================================================================
  function render() {
    document.getElementById('mr-filters').style.display = view === 'registry' ? '' : 'none';
    document.body.classList.toggle('mr-fit', view === 'registry');
    if (view === 'summary') renderSummary(); else renderRegistry();
    syncClearFilt();
  }

  function kpi(val, label, sub, tone) {
    return '<div class="pd-card mr-kpi' + (tone ? ' ' + tone : '') + '">' +
      '<div class="mr-kpi-val">' + esc(val) + '</div>' +
      '<div class="mr-kpi-lbl">' + esc(label) + '</div>' +
      (sub ? '<div class="mr-kpi-sub">' + esc(sub) + '</div>' : '') + '</div>';
  }

  function renderSummary() {
    var host = document.getElementById('mr-view');
    if (!rows.length) { host.innerHTML = emptyHTML(); wireEmpty(); return; }
    var st = allTradeStats(), T = totals(st), L = legacyTotals(st);

    var h = '<div class="mr-kpis">' +
      kpi(T.total, 'Total MS', 'counted toward the target') +
      kpi(T.submitted, 'Submitted', 'approved, w/ comments or disapproved') +
      kpi(T.app, 'Approved', pct(T.pctApp) + ' of target', 'good') +
      kpi(T.balance, 'Balance', 'not yet submitted', T.balance ? 'warn' : '') +
      kpi(pct(T.progress), 'Progress', 'submitted ÷ target') +
      kpi(T.unassigned, 'Ball-in unassigned', 'neither Engg nor Ops', T.unassigned ? 'bad' : '') +
      '</div>';

    // ---- the SUMMARY table, column for column ----
    h += '<div class="pd-card mr-tablecard"><table class="mr-sumtable"><thead>' +
      '<tr class="mr-sum-grp">' +
        '<th colspan="3">MS DETAILS</th>' +
        '<th>TARGET</th>' +
        '<th colspan="3">SUBMITTED</th>' +
        '<th colspan="4">BALANCE ATTACHMENT</th>' +
        '<th colspan="4">APPROVAL STATUS</th>' +
        '<th colspan="4">BALL IN COURT</th></tr>' +
      '<tr><th>No.</th><th>Trade</th><th>Code</th>' +
        '<th class="mr-r">Total MS</th>' +
        '<th class="mr-r">Subm.</th><th class="mr-r">%</th><th class="mr-r">Balance</th>' +
        ATTACH.map(function (a) { return '<th class="mr-r">' + a[1] + '</th>'; }).join('') +
        '<th class="mr-r">App</th><th class="mr-r">AWC</th><th class="mr-r">Dis</th><th class="mr-r">% App</th>' +
        '<th class="mr-r">Engg</th><th class="mr-r">Ops</th><th class="mr-r">Closed</th><th class="mr-r">Unassigned</th>' +
      '</tr></thead><tbody>';

    st.forEach(function (s, i) {
      var zero = !s.total;
      h += '<tr class="mr-sumrow' + (zero ? ' mr-zero' : '') + '" data-trade="' + esc(s.code) + '">' +
        '<td class="mr-mut">' + (i + 1) + '</td>' +
        '<td class="mr-sum-trade">' + esc(s.name) + '</td>' +
        '<td><span class="mr-code">' + esc(s.code) + '</span></td>' +
        '<td class="mr-r mr-b">' + s.total + '</td>' +
        '<td class="mr-r">' + s.submitted + '</td>' +
        '<td class="mr-r">' + (zero ? '—' : pct(s.progress)) + '</td>' +
        '<td class="mr-r">' + s.balance + '</td>' +
        ATTACH.map(function (a) {
          return '<td class="mr-r' + (s.bal[a[0]] ? ' mr-bal' : '') + '">' + s.bal[a[0]] + '</td>';
        }).join('') +
        '<td class="mr-r">' + s.app + '</td><td class="mr-r">' + s.awc + '</td><td class="mr-r">' + s.dis + '</td>' +
        '<td class="mr-r">' + (zero ? '—' : pct(s.pctApp)) + '</td>' +
        '<td class="mr-r">' + s.engg + '</td><td class="mr-r">' + s.ops + '</td>' +
        '<td class="mr-r">' + s.closed + '</td>' +
        '<td class="mr-r' + (s.unassigned ? ' mr-bal' : '') + '">' + s.unassigned + '</td></tr>';
    });
    h += '<tr class="mr-sumtotal"><td></td><td>TOTAL</td><td></td>' +
      '<td class="mr-r">' + T.total + '</td><td class="mr-r">' + T.submitted + '</td>' +
      '<td class="mr-r">' + pct(T.progress) + '</td><td class="mr-r">' + T.balance + '</td>' +
      ATTACH.map(function (a) { return '<td class="mr-r">' + T.bal[a[0]] + '</td>'; }).join('') +
      '<td class="mr-r">' + T.app + '</td><td class="mr-r">' + T.awc + '</td><td class="mr-r">' + T.dis + '</td>' +
      '<td class="mr-r">' + pct(T.pctApp) + '</td>' +
      '<td class="mr-r">' + T.engg + '</td><td class="mr-r">' + T.ops + '</td>' +
      '<td class="mr-r">' + T.closed + '</td><td class="mr-r">' + T.unassigned + '</td></tr>';
    h += '</tbody></table></div>';

    // ---- reconciliation: say where this differs from the workbook, and why ----
    h += reconcileHTML(T, L);
    host.innerHTML = h;
    host.querySelectorAll('.mr-sumrow').forEach(function (tr) {
      tr.onclick = function () { drillTo(tr.dataset.trade); };
    });
  }

  // The two workbook defects, stated rather than silently corrected — the same
  // treatment material-submittal gives its own reconciliation note.
  function reconcileHTML(T, L) {
    var notes = [];
    if (Math.abs(T.progress - L.progress) > 0.0005) {
      notes.push('<li><strong>Progress and % Approved are aggregated here, not averaged.</strong> ' +
        'The workbook\'s total row uses <code>AVERAGE</code> of the twelve trade percentages ' +
        '(including trades with a zero target) while every other figure on that row is a sum — so it prints ' +
        '<strong>' + esc(pct(L.progress)) + '</strong> progress where the register\'s own numbers give ' +
        '<strong>' + esc(pct(T.progress)) + '</strong> (' + T.submitted + ' ÷ ' + T.total + ').</li>');
    }
    if (T.unassigned) {
      notes.push('<li><strong>Ball in court now accounts for every counted item.</strong> ' +
        'The workbook counts only <code>engg</code> and <code>ops</code>, but the register\'s own vocabulary is ' +
        'Open / Ops / Closed — so <strong>' + T.unassigned + '</strong> item' + (T.unassigned === 1 ? '' : 's') +
        ' sitting at “Open” fell into neither column and its Engineering total read 0. ' +
        'Set each one to Engg or Ops to clear this.</li>');
    }
    if (!notes.length) return '';
    return '<div class="pd-card mr-note"><div class="mr-note-hd">' + ico('bulb', 15) +
      ' Differences from the source workbook</div><ul>' + notes.join('') + '</ul></div>';
  }

  function drillTo(trade) {
    filters.trade = trade;
    var s = document.getElementById('mr-f-trade'); if (s) s.value = trade;
    switchTab('registry');
  }

  // ---- Registry (the 4-level tree) ----------------------------------------
  function matches(r) {
    if (filters.countedOnly && !counted(r)) return false;
    if (filters.trade && (r.trade_code || '') !== filters.trade) return false;
    if (filters.status && statusOf(r) !== filters.status) return false;
    if (filters.ballin && ballOf(r) !== filters.ballin) return false;
    if (filters.q) {
      var hay = [r.ms_code, r.title, r.group_name, r.subgroup_name, r.trade_name, r.responsible]
        .filter(Boolean).join(' ').toLowerCase();
      if (hay.indexOf(filters.q.toLowerCase()) === -1) return false;
    }
    return true;
  }
  function anyFilter() {
    return !!(filters.q || filters.trade || filters.status || filters.ballin || filters.countedOnly);
  }

  // Build the tree from the flat rows. Structural rows own the items that follow
  // them, exactly as the workbook's indent staircase does.
  function buildModel() {
    var out = [], curT = null, curG = null, curS = null;
    var pend = [];
    function flushHeaders() { pend.forEach(function (p) { out.push(p); }); pend = []; }
    rows.forEach(function (r) {
      if (r.node_kind === 'trade')    { curT = r; curG = curS = null; pend = [{ lvl: 1, r: r }]; return; }
      if (r.node_kind === 'group')    { curG = r; curS = null; pend = pend.concat([{ lvl: 2, r: r }]); return; }
      if (r.node_kind === 'subgroup') { curS = r; pend = pend.concat([{ lvl: 3, r: r }]); return; }
      if (!matches(r)) return;
      // Only paint a header once one of its items survives the filter — otherwise
      // a search paints empty group rows and reads as "found nothing".
      flushHeaders();
      var tk = 't:' + (curT && curT.id), gk = 'g:' + (curG && curG.id), sk = 's:' + (curS && curS.id);
      if (curT && collapsed[tk]) return;
      if (curG && collapsed[gk]) return;
      if (curS && collapsed[sk]) return;
      out.push({ lvl: 4, r: r });
    });
    return out;
  }

  function renderRegistry() {
    var host = document.getElementById('mr-view');
    if (!rows.length) { host.innerHTML = emptyHTML(); wireEmpty(); return; }
    var model = buildModel();
    var shownItems = model.filter(function (m) { return m.lvl === 4; }).length;
    var totalItems = rows.filter(isItem).length;
    document.getElementById('mr-count').textContent = 'Showing ' + shownItems + ' of ' + totalItems;

    var HEAD = ['<th class="mr-fz1">Code</th>', '<th class="mr-fz2">Method Statement</th>',
      '<th>Rev</th>', '<th>Plan Subm.</th>', '<th>Actual Subm.</th>',
      '<th>Plan Appr.</th>', '<th>Actual Appr.</th>', '<th>Status</th>', '<th>Ball In</th>',
      ATTACH.map(function (a) { return a[1]; }).join('</th><th class="mr-att">').replace(/^/, '<th class="mr-att">') + '</th>',
      '<th>Pri</th>', '<th>Resp.</th>', '<th>Target</th>', '<th class="mr-doccol">Ref</th>'];
    if (canWrite) HEAD.push('<th class="mr-actcol"></th>');
    var SPAN = 0;
    // The attachment entry above is four <th> in one string — count them properly,
    // because every group row and the empty state span this number.
    HEAD.forEach(function (s) { SPAN += (s.match(/<th/g) || []).length; });

    var h = '<div class="pd-card mr-tablecard"><table class="mr-table"><thead><tr>' +
      HEAD.join('') + '</tr></thead><tbody>';
    if (!shownItems) {
      h += '<tr><td colspan="' + SPAN + '" style="text-align:center;padding:34px;" class="mr-mut">' +
        'No method statements match these filters.</td></tr>';
    }
    model.forEach(function (m) {
      var r = m.r;
      if (m.lvl < 4) {
        var key = (m.lvl === 1 ? 't:' : m.lvl === 2 ? 'g:' : 's:') + r.id;
        var label = m.lvl === 1 ? (r.trade_name || r.title) : m.lvl === 2 ? (r.group_name || r.title) : (r.subgroup_name || r.title);
        var isColl = !!collapsed[key];
        h += '<tr class="mr-grp mr-lvl-' + m.lvl + '" data-key="' + esc(key) + '"><td colspan="' + SPAN + '">' +
          '<span class="mr-caret' + (isColl ? ' mr-caret-col' : '') + '">' + ico('chevronDown', 12) + '</span>' +
          (r.trade_code && m.lvl === 1 ? '<span class="mr-code mr-code-lvl">' + esc(r.trade_code) + '</span>' : '') +
          '<span class="mr-grp-txt">' + esc(label || '(untitled)') + '</span>' +
          (m.lvl === 1 ? '<span class="mr-grp-count">' + tradeStats(r.trade_code).total + ' counted</span>' : '') +
          '</td></tr>';
        return;
      }
      var s = statusOf(r), meta = statusMeta(s);
      h += '<tr data-id="' + esc(r.id) + '"' + (counted(r) ? '' : ' class="mr-uncounted"') +
          ' title="' + (counted(r) ? '' : 'Not counted toward the target (workbook N=0)') + '">' +
        '<td class="mr-fz1"><span class="mr-code">' + esc(r.ms_code || r.seq_no || '—') + '</span></td>' +
        '<td class="mr-fz2"><div class="mr-item">' + esc(r.title || '(untitled)') +
          (counted(r) ? '' : ' <span class="mr-nc">not counted</span>') + '</div></td>' +
        '<td class="mr-r">' + esc(r.latest_revision == null ? '' : r.latest_revision) + '</td>' +
        '<td class="mr-nowrap mr-mut">' + fmtDate(r.plan_submission_date) + '</td>' +
        '<td class="mr-nowrap">' + fmtDate(r.actual_submission_date) + '</td>' +
        '<td class="mr-nowrap mr-mut">' + fmtDate(r.plan_approval_date) + '</td>' +
        '<td class="mr-nowrap">' + fmtDate(r.actual_approval_date) + '</td>' +
        '<td>' + (s ? '<span class="mr-pill ' + (meta ? meta.cls : 'mr-s-open') + '">' + esc(s) + '</span>' : '<span class="mr-mut">—</span>') + '</td>' +
        '<td>' + (ballOf(r) ? '<span class="mr-ball">' + esc(ballOf(r)) + '</span>' : '<span class="mr-mut">—</span>') + '</td>' +
        ATTACH.map(function (a) {
          return '<td class="mr-att">' + (r[a[0]]
            ? '<span class="mr-ok" title="' + a[1] + ' complete">' + ico('check', 13) + '</span>'
            : '<span class="mr-bal-dot" title="' + a[1] + ' outstanding">balance</span>') + '</td>';
        }).join('') +
        '<td class="mr-r">' + (r.priority ? '<span class="mr-pri mr-pri-' + r.priority + '">' + r.priority + '</span>' : '') + '</td>' +
        '<td class="mr-nowrap">' + esc(r.responsible || '') + '</td>' +
        '<td class="mr-nowrap mr-mut">' + fmtDate(r.target_date) + '</td>' +
        '<td class="mr-doccol">' + (r.reference_link
          ? '<a class="mr-filebtn" href="' + esc(r.reference_link) + '" target="_blank" rel="noopener" title="Open the reference document">' + ico('link', 14) + '</a>'
          : '<span class="mr-mut">—</span>') + '</td>' +
        (canWrite ? '<td class="mr-actcol"><button class="pd-btn mr-iconbtn" data-edit="' + esc(r.id) + '" title="Edit">' + ico('pencil', 15) + '</button> ' +
          '<button class="pd-btn mr-iconbtn mr-iconbtn-del" data-del="' + esc(r.id) + '" title="Delete">' + ico('trash', 15) + '</button></td>' : '') +
        '</tr>';
    });
    h += '</tbody></table></div>';
    host.innerHTML = h;
    wireRegistry();
  }

  function wireRegistry() {
    var host = document.getElementById('mr-view');
    if (window.Icons && Icons.hydrate) Icons.hydrate(host);
    host.querySelectorAll('.mr-grp').forEach(function (tr) {
      tr.onclick = function () { var k = tr.dataset.key; collapsed[k] = !collapsed[k]; renderRegistry(); };
    });
    host.querySelectorAll('[data-edit]').forEach(function (b) {
      b.onclick = function (e) { e.stopPropagation(); openForm(rows.find(function (r) { return String(r.id) === b.dataset.edit; })); };
    });
    host.querySelectorAll('[data-del]').forEach(function (b) {
      b.onclick = function (e) { e.stopPropagation(); delRow(b.dataset.del); };
    });
    host.querySelectorAll('.mr-filebtn').forEach(function (a) {
      a.onclick = function (e) { e.stopPropagation(); };
    });
  }

  function emptyHTML() {
    return '<div class="pd-card mr-empty"><h3>No method statements yet</h3>' +
      '<p>Import the Method Registry Tracker workbook to load the register, or add statements one at a time.</p>' +
      (canWrite ? '<p style="margin-top:14px;"><button class="pd-btn pd-btn-primary" id="mr-e-imp">Import from Excel</button> ' +
        '<button class="pd-btn" id="mr-e-add">Add a method statement</button></p>' : '') + '</div>';
  }
  function wireEmpty() {
    var a = document.getElementById('mr-e-imp'); if (a) a.onclick = function () { document.getElementById('mr-file').click(); };
    var b = document.getElementById('mr-e-add'); if (b) b.onclick = function () { openForm(null); };
  }

  // ==========================================================================
  // CRUD
  // ==========================================================================
  function openForm(r) {
    if (!canWrite) return;
    r = r || {};
    var isNew = !r.id;
    function fld(label, inner) {
      return '<label class="mr-fld"><span>' + esc(label) + '</span>' + inner + '</label>';
    }
    function txt(k, v, type) {
      return '<input class="pd-input" data-k="' + k + '" type="' + (type || 'text') + '" value="' + esc(v == null ? '' : v) + '" />';
    }
    function sel(k, list, cur, blank) {
      return '<select class="pd-select" data-k="' + k + '">' +
        (blank ? '<option value="">—</option>' : '') +
        list.map(function (o) {
          var val = Array.isArray(o) ? o[0] : o, lab = Array.isArray(o) ? o[1] : o;
          return '<option value="' + esc(val) + '"' + (String(cur || '') === String(val) ? ' selected' : '') + '>' + esc(lab) + '</option>';
        }).join('') + '</select>';
    }
    var m = UI.modal(
      '<div class="pd-modal-header"><h2 style="margin:0;">' + (isNew ? 'Add' : 'Edit') + ' method statement</h2>' +
        '<button class="pd-btn" id="mr-x">&times;</button></div>' +
      '<div class="mr-form">' +
        fld('Trade', sel('trade_code', TRADES, r.trade_code, true)) +
        fld('No. (seq)', txt('seq_no', r.seq_no)) +
        fld('Group', txt('group_name', r.group_name)) +
        fld('Sub-group', txt('subgroup_name', r.subgroup_name)) +
        '<label class="mr-fld mr-fld-wide"><span>Method statement title</span>' +
          '<input class="pd-input" data-k="title" value="' + esc(r.title || '') + '" /></label>' +
        fld('Status', sel('status', STATUS_ORDER, statusOf(r), true)) +
        fld('Ball in court', sel('ball_in', BALL_IN, r.ball_in, true)) +
        fld('Planned submission', txt('plan_submission_date', (r.plan_submission_date || '').slice(0, 10), 'date')) +
        fld('Actual submission', txt('actual_submission_date', (r.actual_submission_date || '').slice(0, 10), 'date')) +
        fld('Planned approval', txt('plan_approval_date', (r.plan_approval_date || '').slice(0, 10), 'date')) +
        fld('Actual approval', txt('actual_approval_date', (r.actual_approval_date || '').slice(0, 10), 'date')) +
        fld('Priority', sel('priority', [1, 2, 3], r.priority, true)) +
        fld('Responsible', txt('responsible', r.responsible)) +
        fld('Target date', txt('target_date', (r.target_date || '').slice(0, 10), 'date')) +
        '<label class="mr-fld mr-fld-wide"><span>Reference link</span>' +
          '<input class="pd-input" data-k="reference_link" value="' + esc(r.reference_link || '') + '" /></label>' +
        '<div class="mr-fld mr-fld-wide"><span>Prerequisite attachments</span><div class="mr-attrow">' +
          ATTACH.map(function (a) {
            return '<label><input type="checkbox" data-k="' + a[0] + '"' + (r[a[0]] ? ' checked' : '') + ' /> ' + a[1] + '</label>';
          }).join('') + '</div></div>' +
        '<div class="mr-fld mr-fld-wide"><label class="mr-countchk"><input type="checkbox" data-k="counts"' +
          (r.counts === false ? '' : ' checked') + ' /> <span><strong>Counts toward the target</strong>' +
          '<small>Clear this for a statement that is named but not yet part of the programme — ' +
          'the Summary excludes it, matching the workbook\'s N flag.</small></span></label></div>' +
      '</div>' +
      '<div class="pd-modal-actions"><button class="pd-btn" id="mr-cancel">Cancel</button>' +
        '<button class="pd-btn pd-btn-primary" id="mr-save">Save</button></div>', { noBackdropClose: true });

    m.el.querySelector('#mr-x').onclick = m.close;
    m.el.querySelector('#mr-cancel').onclick = m.close;
    m.el.querySelector('#mr-save').onclick = async function () {
      var patch = {};
      m.el.querySelectorAll('[data-k]').forEach(function (el) {
        var k = el.dataset.k;
        if (el.type === 'checkbox') patch[k] = el.checked;
        else patch[k] = el.value === '' ? null : el.value;
      });
      if (patch.priority) patch.priority = +patch.priority;
      patch.trade_name = TRADE_NAME[patch.trade_code] || null;
      // The workbook composes the code as trade || seq; keep that rule.
      patch.ms_code = (patch.trade_code && patch.seq_no) ? (patch.trade_code + patch.seq_no) : (r.ms_code || null);
      if (!patch.title) { UI.toast('A title is required.', 'error'); return; }
      try {
        if (isNew) {
          patch.project_id = pid; patch.created_by = UID;
          var ins = await sb().from(TABLE).insert(patch).select().single();
          if (ins.error) throw ins.error;
          rows.push(ins.data);
        } else {
          var up = await sb().from(TABLE).update(patch).eq('id', r.id);
          if (up.error) throw up.error;
          Object.assign(r, patch);
        }
        m.close(); syncFilterOptions(); render();
        UI.toast(isNew ? 'Method statement added.' : 'Saved.');
      } catch (e) { UI.toast('Save failed: ' + (e.message || e), 'error'); }
    };
  }

  async function delRow(id) {
    var r = rows.find(function (x) { return String(x.id) === String(id); });
    if (!r) return;
    if (!confirm('Delete "' + (r.title || r.ms_code || 'this method statement') + '"?')) return;
    try {
      var res = await sb().from(TABLE).delete().eq('id', id);
      if (res.error) throw res.error;
      rows = rows.filter(function (x) { return String(x.id) !== String(id); });
      render(); UI.toast('Deleted.');
    } catch (e) { UI.toast('Delete failed: ' + (e.message || e), 'error'); }
  }

  async function clearAll() {
    if (!isAdmin) return;
    var m = UI.modal('<h2 style="margin-top:0;">Clear the method register</h2>' +
      '<p>This deletes <strong>every</strong> method statement and level for <strong>' + esc(pid) + '</strong>.</p>' +
      '<p>Type the project id to confirm:</p><input class="pd-input" id="mr-confirm" />' +
      '<div class="pd-modal-actions"><button class="pd-btn" id="mr-cc">Cancel</button>' +
      '<button class="pd-btn pd-btn-danger" id="mr-cok">Delete all</button></div>', { noBackdropClose: true });
    m.el.querySelector('#mr-cc').onclick = m.close;
    m.el.querySelector('#mr-cok').onclick = async function () {
      if (m.el.querySelector('#mr-confirm').value.trim() !== pid) { UI.toast('Project id does not match.', 'error'); return; }
      try {
        var res = await sb().from(TABLE).delete().eq('project_id', pid);
        if (res.error) throw res.error;
        rows = []; m.close(); render(); UI.toast('Register cleared.');
      } catch (e) { UI.toast('Clear failed: ' + (e.message || e), 'error'); }
    };
  }

  // ==========================================================================
  // Import — the Method Registry Tracker workbook
  // ==========================================================================
  // ⚠️ Read cells as FORMATTED TEXT (raw:false). SheetJS returns the cell showing
  // 06-Aug-26 as 2026-08-05T15:59:17Z, so local getters land a day out east of
  // Greenwich — the same trap both sibling registers document.
  function gridOf(ws) {
    var ref = ws['!ref'] || 'A1';
    var R = XLSX.utils.decode_range(ref);
    var maxC = Math.min(R.e.c, 60), maxR = Math.min(R.e.r, 4000);
    var out = [];
    for (var r = R.s.r; r <= maxR; r++) {
      var row = [];
      for (var c = R.s.c; c <= maxC; c++) {
        var cell = ws[XLSX.utils.encode_cell({ r: r, c: c })];
        row.push(cell ? (cell.w != null ? String(cell.w).trim() : String(cell.v).trim()) : '');
      }
      out.push(row);
    }
    return out;
  }
  function parseDate(v) {
    if (!v || v === '-') return null;
    var s = String(v).trim();
    var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
    if (m) return m[1] + '-' + m[2] + '-' + m[3];
    // dd-MMM-yy / dd-MMM-yyyy
    m = /^(\d{1,2})[-\/ ]([A-Za-z]{3})[a-z]*[-\/ ](\d{2,4})$/.exec(s);
    if (m) {
      var mi = MNAME.indexOf(m[2][0].toUpperCase() + m[2].slice(1, 3).toLowerCase());
      if (mi >= 0) {
        var y = +m[3]; if (y < 100) y += 2000;
        return y + '-' + String(mi + 1).padStart(2, '0') + '-' + String(+m[1]).padStart(2, '0');
      }
    }
    m = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(s);           // dd/mm/yyyy
    if (m) return m[3] + '-' + String(+m[2]).padStart(2, '0') + '-' + String(+m[1]).padStart(2, '0');
    return null;
  }
  // Excel's zero date, used by the workbook's own MAX() guards, is not a date.
  function realDate(d) {
    if (!d) return null;
    var y = +String(d).slice(0, 4);
    return (y < 2015 || y > 2100) ? null : d;
  }

  var COL = { trade: 0, no: 1, t1: 9, t2: 10, t3: 11, t4: 12, n: 13, rev: 14,
    planSub: 19, actSub: 20, rev1p: 21, rev1a: 22, rev2p: 23, rev2a: 24,
    rev3p: 25, rev3a: 26, rev4p: 27, rev4a: 28, planAppr: 29, actAppr: 30,
    status: 31, ballIn: 32, apprSheets: 33, hirac: 36, qcc: 37, mas: 38, isd: 39,
    link: 40, priority: 43, responsible: 44, target: 45 };

  function normStatus(v) {
    var s = String(v == null ? '' : v).trim();
    if (!s || s === '-') return null;
    var k = LEGACY_STATUS[s.toLowerCase()];
    if (k !== undefined) return k || null;
    var lo = s.toLowerCase();
    if (lo === 'approved') return 'Approved';
    if (lo.indexOf('comment') !== -1) return 'Approved w/ Comments';
    if (lo.indexOf('disappr') !== -1) return 'Disapproved';
    if (lo === 'open') return 'Open';
    return s;
  }
  function normBall(v) {
    var s = String(v == null ? '' : v).trim().toLowerCase();
    if (!s || s === '-') return null;
    if (s === 'engg' || s === 'eng' || s === 'engineering') return 'Engg';
    if (s === 'ops') return 'Ops';
    if (s === 'closed') return 'Closed';
    if (s === 'open') return 'Open';
    return String(v).trim();
  }

  function parseWorkbook(wb) {
    // The registry sheet is the one whose row 8-ish header carries "Method
    // Statement Title"; rank by how many method statements it yields.
    var best = null;
    wb.SheetNames.forEach(function (nm) {
      var g = gridOf(wb.Sheets[nm]);
      var hdr = -1;
      for (var i = 0; i < Math.min(g.length, 40); i++) {
        var joined = g[i].join('|').toLowerCase();
        if (joined.indexOf('method statement title') !== -1) { hdr = i; break; }
      }
      if (hdr < 0) return;
      var recs = parseGrid(g, hdr);
      if (!best || recs.items > best.items) best = { sheet: nm, hdr: hdr, grid: g, recs: recs.records, items: recs.items };
    });
    return best;
  }

  function parseGrid(g, hdr) {
    var out = [], items = 0, order = 0;
    var curTrade = null, curTradeName = null, curGroup = null, curSub = null;
    for (var i = hdr + 1; i < g.length; i++) {
      var row = g[i];
      var t1 = row[COL.t1] || '', t2 = row[COL.t2] || '', t3 = row[COL.t3] || '', t4 = row[COL.t4] || '';
      var code = (row[COL.trade] || '').trim(), no = (row[COL.no] || '').trim();
      if (!t1 && !t2 && !t3 && !t4) continue;

      if (t1) {                                   // trade header
        curTrade = code || null; curTradeName = t1.replace(/\s+/g, ' ').trim();
        curGroup = curSub = null;
        out.push({ node_kind: 'trade', trade_code: curTrade, trade_name: curTradeName,
          seq_no: no || null, title: curTradeName, counts: false, sort_order: order++ });
        continue;
      }
      if (t2) {                                   // group
        curGroup = t2.replace(/\s+/g, ' ').trim(); curSub = null;
        out.push({ node_kind: 'group', trade_code: curTrade, trade_name: curTradeName,
          group_name: curGroup, seq_no: no || null, title: curGroup, counts: false, sort_order: order++ });
        continue;
      }
      if (t3) {                                   // sub-group
        curSub = t3.replace(/\s+/g, ' ').trim();
        out.push({ node_kind: 'subgroup', trade_code: curTrade, trade_name: curTradeName,
          group_name: curGroup, subgroup_name: curSub, seq_no: no || null,
          title: curSub, counts: false, sort_order: order++ });
        continue;
      }
      // a method statement
      var nRaw = String(row[COL.n] == null ? '' : row[COL.n]).trim();
      var subs = [];
      [[COL.rev1p, COL.rev1a], [COL.rev2p, COL.rev2a], [COL.rev3p, COL.rev3a], [COL.rev4p, COL.rev4a]]
        .forEach(function (pair, idx) {
          var p = realDate(parseDate(row[pair[0]])), a = realDate(parseDate(row[pair[1]]));
          if (p || a) subs.push({ rev: idx + 1, planned: p, actual: a });
        });
      items++;
      out.push({
        node_kind: null,
        trade_code: curTrade, trade_name: curTradeName,
        group_name: curGroup, subgroup_name: curSub,
        seq_no: no || null,
        ms_code: (code || (curTrade && no ? curTrade + no : null)) || null,
        title: t4.replace(/\s+/g, ' ').trim(),
        // ⚠️ N=1 is the workbook's "counts toward the target" flag.
        counts: nRaw === '1',
        latest_revision: subs.length || null,
        plan_submission_date:   realDate(parseDate(row[COL.planSub])),
        actual_submission_date: realDate(parseDate(row[COL.actSub])),
        submissions: subs,
        plan_approval_date:   realDate(parseDate(row[COL.planAppr])),
        actual_approval_date: realDate(parseDate(row[COL.actAppr])),
        status: normStatus(row[COL.status]),
        ball_in: normBall(row[COL.ballIn]),
        approved_sheets: /^\d+$/.test(String(row[COL.apprSheets] || '').trim()) ? +row[COL.apprSheets] : null,
        // 'balance' in the sheet means OUTSTANDING, so done = not balance.
        hirac_done: String(row[COL.hirac] || '').trim().toLowerCase() !== 'balance' && !!String(row[COL.hirac] || '').trim(),
        qcc_done:   String(row[COL.qcc]   || '').trim().toLowerCase() !== 'balance' && !!String(row[COL.qcc]   || '').trim(),
        mas_done:   String(row[COL.mas]   || '').trim().toLowerCase() !== 'balance' && !!String(row[COL.mas]   || '').trim(),
        isd_done:   String(row[COL.isd]   || '').trim().toLowerCase() !== 'balance' && !!String(row[COL.isd]   || '').trim(),
        reference_link: (String(row[COL.link] || '').trim().indexOf('http') === 0) ? String(row[COL.link]).trim() : null,
        priority: /^[123]$/.test(String(row[COL.priority] || '').trim()) ? +row[COL.priority] : null,
        responsible: String(row[COL.responsible] || '').trim() || null,
        target_date: realDate(parseDate(row[COL.target])),
        sort_order: order++
      });
    }
    return { records: out, items: items };
  }

  async function onFile(e) {
    var f = e.target.files && e.target.files[0];
    e.target.value = '';
    if (!f) return;
    var m = UI.modal('<h2 style="margin-top:0;">Import method register</h2><p id="mr-imp-msg">Reading…</p>',
      { noBackdropClose: true });
    var msg = m.el.querySelector('#mr-imp-msg');
    try {
      var buf = await f.arrayBuffer();
      var wb = XLSX.read(buf, { type: 'array', cellDates: false, sheetRows: 4000 });
      var got = parseWorkbook(wb);
      if (!got || !got.items) { msg.textContent = 'No “Method Statement Title” column found in this workbook.'; return; }
      var counted = got.recs.filter(function (r) { return !r.node_kind && r.counts; }).length;
      msg.innerHTML = 'Sheet <strong>' + esc(got.sheet) + '</strong> — <strong>' + got.items +
        '</strong> method statements (<strong>' + counted + '</strong> counted toward the target), ' +
        (got.recs.length - got.items) + ' level rows.' +
        '<label style="display:block;margin-top:12px;"><input type="checkbox" id="mr-imp-replace" checked /> ' +
        'Replace the existing register for this project</label>' +
        '<div class="pd-modal-actions"><button class="pd-btn" id="mr-imp-cancel">Cancel</button>' +
        '<button class="pd-btn pd-btn-primary" id="mr-imp-go">Import</button></div>';
      m.el.querySelector('#mr-imp-cancel').onclick = m.close;
      m.el.querySelector('#mr-imp-go').onclick = async function () {
        var replace = m.el.querySelector('#mr-imp-replace').checked;
        msg.textContent = 'Importing…';
        try {
          if (replace) {
            var d = await sb().from(TABLE).delete().eq('project_id', pid);
            if (d.error) throw d.error;
          }
          var payload = got.recs.map(function (r) {
            return Object.assign({}, r, { project_id: pid, created_by: UID });
          });
          for (var i = 0; i < payload.length; i += 200) {
            var res = await sb().from(TABLE).insert(payload.slice(i, i + 200));
            if (res.error) throw res.error;
            msg.textContent = 'Importing… ' + Math.min(i + 200, payload.length) + ' / ' + payload.length;
            await new Promise(function (r2) { setTimeout(r2, 0); });
          }
          m.close(); UI.toast('Imported ' + got.items + ' method statements.');
          await load();
        } catch (err) { msg.textContent = 'Import failed: ' + (err.message || err); }
      };
    } catch (err) { msg.textContent = 'Could not read the workbook: ' + (err.message || err); }
  }

  // ---- export --------------------------------------------------------------
  function exportExcel() {
    var st = allTradeStats(), T = totals(st);
    var sum = st.map(function (s, i) {
      var o = { 'No.': i + 1, Trade: s.name, Code: s.code, 'Total MS': s.total,
        Submitted: s.submitted, Progress: s.progress, Balance: s.balance };
      ATTACH.forEach(function (a) { o[a[1] + ' balance'] = s.bal[a[0]]; });
      o.App = s.app; o.AWC = s.awc; o.Dis = s.dis; o['% App'] = s.pctApp;
      o.Engg = s.engg; o.Ops = s.ops; o.Closed = s.closed; o.Unassigned = s.unassigned;
      return o;
    });
    sum.push({ 'No.': '', Trade: 'TOTAL', Code: '', 'Total MS': T.total, Submitted: T.submitted,
      Progress: T.progress, Balance: T.balance, App: T.app, AWC: T.awc, Dis: T.dis,
      '% App': T.pctApp, Engg: T.engg, Ops: T.ops, Closed: T.closed, Unassigned: T.unassigned });

    var reg = rows.filter(isItem).map(function (r) {
      var o = { Code: r.ms_code || '', 'No.': r.seq_no || '', Trade: r.trade_name || '',
        Group: r.group_name || '', 'Sub-group': r.subgroup_name || '',
        'Method Statement': r.title || '', Counted: r.counts === false ? 'No' : 'Yes',
        Rev: r.latest_revision == null ? '' : r.latest_revision,
        'Plan Subm.': r.plan_submission_date || '', 'Actual Subm.': r.actual_submission_date || '',
        'Plan Appr.': r.plan_approval_date || '', 'Actual Appr.': r.actual_approval_date || '',
        Status: statusOf(r), 'Ball In': r.ball_in || '' };
      ATTACH.forEach(function (a) { o[a[1]] = r[a[0]] ? 'Yes' : 'balance'; });
      o.Priority = r.priority || ''; o.Responsible = r.responsible || '';
      o['Target Date'] = r.target_date || ''; o.Reference = r.reference_link || '';
      return o;
    });
    var wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sum), 'SUMMARY');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(reg), 'Method Registry');
    XLSX.writeFile(wb, 'Method Register - ' + (projName() || pid) + '.xlsx');
  }
  function projName() {
    var s = document.getElementById('mr-project');
    return s && s.selectedIndex >= 0 ? s.options[s.selectedIndex].textContent : '';
  }

  // ==========================================================================
  // Shell
  // ==========================================================================
  function switchTab(v) {
    view = v;
    document.querySelectorAll('.mr-tab').forEach(function (t) {
      t.classList.toggle('active', t.dataset.view === v);
    });
    render();
  }
  function syncClearFilt() {
    var b = document.getElementById('mr-f-clear');
    if (b) b.hidden = !anyFilter();
  }
  function syncFilterOptions() {
    var t = document.getElementById('mr-f-trade');
    var present = {};
    rows.forEach(function (r) { if (r.trade_code) present[r.trade_code] = 1; });
    t.innerHTML = '<option value="">All trades</option>' + TRADES
      .filter(function (x) { return present[x[0]]; })
      .map(function (x) { return '<option value="' + esc(x[0]) + '">' + esc(x[1]) + '</option>'; }).join('');
    t.value = filters.trade;
    var s = document.getElementById('mr-f-status');
    s.innerHTML = '<option value="">All statuses</option>' +
      STATUS_ORDER.map(function (x) { return '<option>' + esc(x) + '</option>'; }).join('');
    s.value = filters.status;
    var b = document.getElementById('mr-f-ballin');
    b.innerHTML = '<option value="">All ball-in-court</option>' +
      BALL_IN.map(function (x) { return '<option>' + esc(x) + '</option>'; }).join('');
    b.value = filters.ballin;
  }

  async function init(user, profile) {
    UID = (user && user.id) || (profile && profile.id) || null;
    PROFILE = profile;
    isAdmin = !!(profile && (profile.role === 'admin' || profile.role === 'super_admin'));
    canWrite = !!(profile && ['super_admin', 'admin', 'planner'].indexOf(profile.role) !== -1);
    UI.initShell();

    document.getElementById('mr-clear').style.display = isAdmin ? '' : 'none';
    if (!canWrite) {
      ['mr-add', 'mr-import'].forEach(function (id) { var b = document.getElementById(id); if (b) b.style.display = 'none'; });
    }

    var selEl = document.getElementById('mr-project');
    try { projects = (await PDb.getProjects()) || []; } catch (e) { projects = []; }
    projects = projects.filter(function (p) { return !AppAuth.canAccessProject || AppAuth.canAccessProject(profile, p.id); });
    selEl.innerHTML = projects.map(function (p) {
      return '<option value="' + esc(p.id) + '">' + esc(p.name || p.id) + '</option>';
    }).join('');
    // ⚠️ NEVER fall back to the first project — a <select> with no explicit value
    // reports its FIRST OPTION, which silently adopts a project the user never
    // chose. Project-first, same rule as dashboard.html and both sibling modules.
    var stored = sessionStorage.getItem('pd_project');
    var ok = stored && projects.some(function (p) { return String(p.id) === String(stored); });
    if (!ok) { location.replace('../../projects.html'); return; }
    selEl.value = stored;
    pid = stored;
    if (UI.enhanceProjectSelect) UI.enhanceProjectSelect(selEl);
    selEl.addEventListener('change', function () {
      pid = selEl.value;
      sessionStorage.setItem('pd_project', pid);
      collapsed = {};
      filters = { q: '', trade: '', status: '', ballin: '', countedOnly: false };
      document.getElementById('mr-f-search').value = '';
      load();
    });

    document.querySelectorAll('.mr-tab').forEach(function (t) {
      t.onclick = function () { switchTab(t.dataset.view); };
    });
    document.getElementById('mr-add').onclick = function () { openForm(null); };
    document.getElementById('mr-import').onclick = function () { document.getElementById('mr-file').click(); };
    document.getElementById('mr-file').addEventListener('change', onFile);
    document.getElementById('mr-export').onclick = exportExcel;
    document.getElementById('mr-print').onclick = function () { setTimeout(function () { window.print(); }, 60); };
    document.getElementById('mr-clear').onclick = clearAll;

    var q = document.getElementById('mr-f-search'), tmr = null;
    q.addEventListener('input', function () {
      clearTimeout(tmr);
      tmr = setTimeout(function () { filters.q = q.value; render(); }, 160);
    });
    document.getElementById('mr-f-trade').addEventListener('change', function (e) { filters.trade = e.target.value; render(); });
    document.getElementById('mr-f-status').addEventListener('change', function (e) { filters.status = e.target.value; render(); });
    document.getElementById('mr-f-ballin').addEventListener('change', function (e) { filters.ballin = e.target.value; render(); });
    document.getElementById('mr-f-counted').addEventListener('change', function (e) { filters.countedOnly = e.target.checked; render(); });
    document.getElementById('mr-f-clear').onclick = function () {
      filters = { q: '', trade: '', status: '', ballin: '', countedOnly: false };
      q.value = '';
      ['mr-f-trade', 'mr-f-status', 'mr-f-ballin'].forEach(function (id) { document.getElementById(id).value = ''; });
      document.getElementById('mr-f-counted').checked = false;
      render();
    };

    await load();
  }

  return {
    init: init,
    // Exposed for the verification harness as well as the page — the same
    // arrangement both sibling registers use, so their suites can run the
    // SHIPPED functions rather than a reimplementation of them.
    _internals: { tradeStats: tradeStats, totals: totals, legacyTotals: legacyTotals,
      allTradeStats: allTradeStats, parseWorkbook: parseWorkbook, parseGrid: parseGrid,
      parseDate: parseDate, realDate: realDate, normStatus: normStatus, normBall: normBall,
      render: render, switchTab: switchTab, buildModel: buildModel,
      setRows: function (x) { rows = x; }, setPid: function (x) { pid = x; },
      setCanWrite: function (x) { canWrite = x; }, TRADES: TRADES }
  };
})();
